name: vgcn-build
channels:
  - tsnyder
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - ansible=8.5.0=pyhd8ed1ab_0
  - ansible-core=2.15.4=pyh707e725_0
  - appdirs=1.4.4=pyh9f0ad1d_0
  - attrs=23.1.0=pyh71513ae_1
  - autopage=0.5.2=pyhd8ed1ab_0
  - brotlipy=0.7.0=py312h98912ed_1006
  - bzip2=1.0.8=hd590300_5
  - c-ares=1.23.0=hd590300_0
  - ca-certificates=2023.11.17=hbcca054_0
  - certifi=2023.11.17=pyhd8ed1ab_0
  - cffi=1.16.0=py312hf06ca03_0
  - charset-normalizer=3.3.2=pyhd8ed1ab_0
  - cliff=4.4.0=pyhd8ed1ab_0
  - cmd2=2.4.3=py312h7900ff3_1
  - cryptography=41.0.7=py312h4742d6a_1
  - debtcollector=2.5.0=pyhd8ed1ab_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - dogpile.cache=1.2.2=pyhd8ed1ab_1
  - gettext=0.21.1=h27087fc_0
  - idna=3.6=pyhd8ed1ab_0
  - importlib-metadata=7.0.0=pyha770c72_0
  - importlib_metadata=7.0.0=hd8ed1ab_0
  - iso8601=2.1.0=pyhd8ed1ab_0
  - jinja2=3.1.2=pyhd8ed1ab_1
  - jmespath=1.0.1=pyhd8ed1ab_0
  - jsonpatch=1.33=pyhd8ed1ab_0
  - jsonpointer=2.4=py312h7900ff3_3
  - keystoneauth1=5.4.0=pyhd8ed1ab_0
  - krb5=1.20.1=h143b758_1
  - ld_impl_linux-64=2.40=h41732ed_0
  - libcurl=7.88.1=hdc1c0ab_1
  - libedit=3.1.20221030=h5eee18b_0
  - libev=4.33=hd590300_2
  - libexpat=2.5.0=hcb278e6_1
  - libffi=3.4.2=h7f98852_5
  - libgcc-ng=13.2.0=h807b86a_3
  - libglib=2.70.2=h174f98d_4
  - libgomp=13.2.0=h807b86a_3
  - libiconv=1.17=hd590300_1
  - libnghttp2=1.57.0=h2d74bed_0
  - libnsl=2.0.1=hd590300_0
  - libsqlite=3.44.2=h2797004_0
  - libssh2=1.11.0=h0841786_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=2.38.1=h0b41bf4_0
  - libzlib=1.2.13=hd590300_5
  - lz4-c=1.9.3=h9c3ff4c_1
  - markupsafe=2.1.3=py312h98912ed_1
  - msgpack-python=1.0.3=py312hdb19cb5_0
  - ncurses=6.4=h59595ed_2
  - netaddr=0.7.19=py_0
  - netifaces=0.11.0=py312h98912ed_2
  - openssl=3.2.0=hd590300_1
  - openstacksdk=2.0.0=pyhd8ed1ab_0
  - os-service-types=1.7.0=pyh9f0ad1d_0
  - osc-lib=2.9.0=pyhd8ed1ab_0
  - oslo.config=9.2.0=pyhd8ed1ab_0
  - oslo.i18n=6.2.0=pyhd8ed1ab_0
  - oslo.serialization=5.2.0=pyhd8ed1ab_0
  - oslo.utils=6.3.0=pyhd8ed1ab_0
  - packaging=23.2=pyhd8ed1ab_0
  - packer=1.10.0=ha8f183a_0
  - pbr=6.0.0=pyhd8ed1ab_0
  - pcre=8.45=h9c3ff4c_0
  - pip=23.3.1=pyhd8ed1ab_0
  - pixman=0.40.0=h36c2ea0_0
  - platformdirs=4.1.0=pyhd8ed1ab_0
  - prettytable=3.9.0=pyhd8ed1ab_0
  - pycparser=2.21=pyhd8ed1ab_0
  - pyopenssl=23.3.0=pyhd8ed1ab_0
  - pyparsing=3.1.1=pyhd8ed1ab_0
  - pyperclip=1.8.2=pyhd8ed1ab_2
  - pysocks=1.7.1=pyha2e5f31_6
  - python=3.12.0=hab00c5b_0_cpython
  - python-cinderclient=9.4.0=pyhd8ed1ab_0
  - python-keystoneclient=5.2.0=pyhd8ed1ab_0
  - python-novaclient=18.3.0=pyhd8ed1ab_0
  - python-openstackclient=6.3.0=pyhd8ed1ab_0
  - python-tzdata=2023.3=pyhd8ed1ab_0
  - python_abi=3.12=4_cp312
  - pytz=2023.3.post1=pyhd8ed1ab_0
  - pyyaml=6.0.1=py312h98912ed_1
  - qemu=5.0.0=hc4641f2_0
  - readline=8.2=h8228510_1
  - requests=2.31.0=pyhd8ed1ab_0
  - requestsexceptions=1.4.0=py_0
  - resolvelib=1.0.1=pyhd8ed1ab_0
  - rfc3986=2.0.0=pyhd8ed1ab_0
  - setuptools=68.2.2=pyhd8ed1ab_0
  - simplejson=3.19.2=py312h98912ed_0
  - six=1.16.0=pyh6c4a22f_0
  - stevedore=5.1.0=pyhd8ed1ab_0
  - tk=8.6.13=noxft_h4845f30_101
  - typing_extensions=4.9.0=pyha770c72_0
  - tzdata=2023c=h71feb2d_0
  - urllib3=1.26.15=pyhd8ed1ab_0
  - wcwidth=0.2.12=pyhd8ed1ab_0
  - wheel=0.42.0=pyhd8ed1ab_0
  - wrapt=1.16.0=py312h98912ed_0
  - xz=5.2.6=h166bdaf_0
  - yaml=0.2.5=h7f98852_2
  - zipp=3.17.0=pyhd8ed1ab_0
  - zlib=1.2.13=hd590300_5
  - zstd=1.5.2=h8a70e8d_1
