---
- hosts: workers-gpu
  vars_files:
    - "group_vars/all.yml"
    - "group_vars/pulsar.yml"
    - "group_vars/condor.yml"
    - "group_vars/gpu.yml"
  handlers:
    - name: Reload HTCondor
      when: "'condor_service' in service_facts.ansible_facts.services and \
        service_facts.ansible_facts.services['condor.service'].state == 'running'"
      become: true
      ansible.builtin.service:
        name: condor
        state: reloaded
  pre_tasks:
    - name: system update
      ansible.builtin.dnf:
        name: '*'
        state: latest
        exclude: condor*
    - name: Install Pulsar dependencies
      become: yes
      ansible.builtin.dnf:
        state: latest
        name:
          - git
          - python36
          - python3-devel
          - python3-virtualenv
          - python38
          - python38-devel
          - gcc
          - curl
          - libcurl-devel
          - openssl-devel
      when: ansible_os_family == 'RedHat' and ansible_distribution_major_version | int == 8
    - name: Install Pulsar dependencies
      package:
        name:
          - gcc
          - curl
          - git
          - libcurl-devel
          - python-devel
        state: present
      become: true
      when: ansible_os_family == 'RedHat' and ansible_distribution_major_version | int == 9
    - name: Set default version of Python
      ansible.builtin.alternatives:
        name: python
        path: /usr/bin/python3
        link: /usr/bin/python
    - name: Put SELinux in permissive mode, logging actions that would be blocked.
      ansible.builtin.lineinfile:
        path: /etc/selinux/config
        regexp: '^SELINUX='
        line: SELINUX=permissive
    - name: "Deploy docker-stop-1M script"
      ansible.builtin.copy:
        content: |
            #!/bin/bash
            docker ps -f status=running --format '{{ '{{' }}.ID}}: {{ '{{' }}.RunningFor}}' | awk '/months/ && $2 > 1 { print $0 }'|cut -f1 -d':' | xargs docker stop
        dest: /usr/bin/docker-stop-1M
        owner: root
        group: root
        mode: 0755
    - name: Ensure the HTCondor configuration directory exists.
      become: true
      ansible.builtin.file:
        path: /etc/condor
        state: directory
        owner: root
        group: root
        mode: "0755"
    - name: Condor walltime script
      ansible.builtin.copy:
        dest: /etc/condor/meta_walltime.py
        src: meta_walltime.py
        mode: "0755"
      notify: Reload HTCondor
    - name: Check if HTCondor is running.
      ansible.builtin.service_facts:
      register: service_facts
  post_tasks:
    - name: Add firewall rules for NFS
      ansible.posix.firewalld:
        service: "{{ item }}"
        state: enabled
        permanent: true
        immediate: true
      with_items:
        - nfs
        - rpc-bind
        - mountd
    - name: Open Port for HTCondor
      ansible.posix.firewalld:
        port: "{{ htcondor_port }}/tcp"
        state: enabled
        permanent: true
        immediate: true
    - name: Restart Autofs
      ansible.builtin.service:
        name: autofs
        state: restarted
    - name: galaxy account group
      ansible.builtin.group:
        gid: "{{ galaxy_gid }}"
        name: galaxy
        state: present
    - name: galaxy account user
      ansible.builtin.user:
        uid: "{{ galaxy_uid }}"
        name: galaxy
        group: galaxy
        home: /opt/galaxy
        state: present
        comment: Galaxy Service-Acct
        createhome: no
    - ansible.builtin.user:
        name: galaxy
        groups: condor,docker
        append: yes
    - ansible.builtin.dnf:
        name: "{{ packages }}"
        state: absent
      vars:
        packages:
          - libcurl-devel
          - openssl-devel
      become: yes
    - name: Ensure Docker directory extists
      file:
        state: directory
        path: /etc/docker
        mode: '0755'
    - name: Copy Docker daemon.json
      ansible.builtin.copy:
        src: daemon.json
        dest: /etc/docker/daemon.json
        mode: '0644'
    - name: Restart Docker service, in all cases
      ansible.builtin.service:
        name: docker
        state: restarted
    - name: Deploy a signal emitter for telegraf
      ansible.builtin.copy:
        content: |
          #!/bin/bash
          echo '{"alive":1}'
        dest: /bin/iamalive
        owner: telegraf
        group: telegraf
        mode: 0755
  roles:
    - geerlingguy.repo-epel # Install EPEL
    - role: usegalaxy_eu.handy.os_setup
      vars:
        enable_powertools: true # geerlingguy.repo-epel role doesn't enable PowerTools repository
        enable_remap_user: true
        enable_pam_limits: true
        enable_grub: true
        enable_cgroups: false
        enable_journald: true
        enable_install_software: true
        enable_ansible_root_cron: false

    - usegalaxy-eu.autofs
    - usegalaxy-eu.dynmotd

    - geerlingguy.java
    - geerlingguy.docker

    - influxdata.chrony
    - usegalaxy-eu.telegraf

    - galaxyproject.cvmfs
    - galaxyproject.pulsar
    - usegalaxy_eu.cuda
    - usegalaxy_eu.nvidia_container

    - usegalaxy-eu.logrotate
    - role: usegalaxy_eu.handy.os_setup
      vars:
        enable_powertools: false # geerlingguy.repo-epel role doesn't enable PowerTools repository
        enable_remap_user: true  # needs to be at the end, otherwise dnsmasq will occupy 999 slot
        enable_pam_limits: false
        enable_grub: false
        enable_cgroups: false
        enable_journald: false
        enable_install_software: false
        enable_ansible_root_cron: true

    # Applies a 250GB soft and 1TB hard limit on the file size for the condor systemd unit
    - role: usegalaxy-eu.fslimit
      become: yes
      vars:
        ulimit_fsize_unit: "condor.service"
        ulimit_fsize_soft: 268435456000
        ulimit_fsize_hard: 1073741824000
